name: DB Tests

on:
  push:
    paths:
      - 'app/**'
      - 'migrations/**'
      - 'tests/db/**'
  pull_request:
    paths:
      - 'app/**'
      - 'migrations/**'
      - 'tests/db/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Установка Python и Poetry
        uses: ./.github/actions/setup-venv
        with:
          python-version: ${{ matrix.python-version }}

      - name: Тесты БД
        env:
          FLASK_ENV: testing
        run: poetry run pytest -q tests/db
